### PR TITLE
Added keyboard input functionality

### LINKED ISSUE #7: Add Keyboard Support to Calculator
**Is your feature request related to a problem? Please describe.**  
Currently, the calculator only supports touch/mouse inputs and limited keyboard input via using <kbd>tab</kbd> and <kbd>tab</kbd> + <kbd>shift</kbd>. Adding keyboard support will make it and more convenient to use. 

**Describe the solution you'd like**  
Add an event listener to listen to the [keydown event](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event)
and check if the input value matches one of the button for the calculator.

**For Contributors / Suggestions**  
If you would like to help with this task or have a better solution, please leave a comment here. I'll assign the task to you if you would like to contribute!

### PR DESCRIPTION
**Pull request by RubenLeerentveld**
Hi,

In this feature I added keyboard inputs in Button.js

At first: Your calculator is nicely made and well structured, good job!

On the document.onkeydown I validate the input, the following keys are allowed:
1, 2, 3, 4, 5, 6, 7, 8, 9, 0, +, -, /, * and enter.
after that I call the handleInput function. this is were based on the input, an action will be called.

I saw you used an testFunction() on the buttons, that seemed to work, so I used it too!

workflow:
  1. with the numbers I call testFunction after parsing the input to an int.
  2. with the plus, minus, divide and multiply i just call the testFunction
  3. if Enter is pressed, I use '=' as input for the testFunction

notes:
1. Lots of Alert() occured on pressing buttons (not anymore) they may come back.
2. When pressing a number on your keyboard, the css of the buttons do not change (with clicking buttons it does) you may want to look in in to this :)
3. Pressing +, -, / or * nothing shows up on the header, you may want to fix this later on :)
4. Maybe a nice feature for in the future is being able to see the whole sum on the screen, or maybe a history!

That's it!

I had a lot of fun contributing to your project!

Ruben

### CODE REVIEW

**Comment by yingmo55** [comment]
Thanks a lot for your interest and work on this project! I appreciate the help.

I took a look at your code, and this is how I would refactor it:

```javascript
function Button(props) {
    const handleChange = props.onClick;

    const numbers = Array.from('1234567890');
    const operators = Array.from('+-*/.');

		//HANDLE VALIDATED INPUT
    const handleInput = (input) => {
        if(numbers.includes(input)){
            return handleChange(parseInt(input));
        }
         if(operators.includes(input)){
           return handleChange(input);
        }
         if(input === 'Enter'){
           return handleChange('=');
        }

        const value = props.value;
        return handleChange(value)
    }

    //VALIDATE INPUT
    document.onkeydown = function (e){
        if( numbers.includes(e.key) || 
            operators.includes(e.key) ||
            e.key === 'Enter'){
            handleInput(e.key);
        }
    }

    return (
        <button type='button' 
        className={props.className}
        id={props.id} 
        onClick={handleInput}
        value={props.value}
        >{props.value}</button>
    );
}
```

Here are the changes and reasons:

1. Instead of checking individual values using the `||` operator, I added two arrays with numbers     `const numbers = Array.from('1234567890')`and operators symbols `const operators = Array.from('+-*/.')` and then used the array method `.includes()` to check the value. (It also now supports the decimal/period key input) I believe this changes make it easier to maintain the code
2. Instead of chaining `else if` statement, I use `if` statements and the `return` keyword to return the function since the code block after `return` does not execute.
3. the name `testFunction()` was an oversight. I left it when I started the project and forgot about it. I changed it to the corresponding name passed from the component above.

And to answer some of your notes:

> 2. When pressing a number on your keyboard, the css of the buttons do not change (with clicking buttons it does) you may want to look in in to this :)

Currently, the buttons’ CSS changes only under the “hover”, “focus”, and “active” state, and when using a keyboard input, it directly passes the value of the corresponding key to the function, which skips the `<button>` input. I imagine it will be an easy fix.

> 3.  Pressing +, -, / or * nothing shows up on the header, you may want to fix this later on :)

This suggestion is currently an open issue here: [https://github.com/yingmo55/Calculator/issues/8](https://github.com/yingmo55/Calculator/issues/8)

> 4. Maybe a nice feature for in the future is being able to see the whole sum on the screen, or maybe a history!

I will consider adding this or opening an issue for this feature in the future!


Would you like to apply these changes to your current pull request? Thanks again for taking the time to work on the issue!

**Comment by RubenLeerentveld** [comment]
Hi!

Nice refactor!
I implemented the use of the arrays.
I believe we do need an `else` in our function. 
If there is no input from the keyboard: the selected button on the screen needs to be used, which is the `else`
`else{
            const value = props.value;
            handleChange(value);
        }`
        
Thanks for the tip, learned lots from it :)
I pushed the refactor

**Comment by RubenLeerentveld** [comment]
Hi

Nice refactor!
Haven't thought of the arrays myself.
I implemented the 2 arrays in the logic.
Learned lots from it!

ps: pushed new commit

**Comment by yingmo55** [comment]
Thanks again for working on the issue! I'll merge the pull request now.

**Pull request merged**
